# Generated by Django 4.1.7 on 2023-03-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('stock_no',), name='unique_stock_no'),
        ),
    ]
